/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_HealthCloudGA_ContactContacta0CTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_HealthCloudGA_ContactConta0CTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new HealthCloudGA__ContactContactRelation__c());
    }
}